from __future__ import annotations

import glob
import json
import os
import re
import shutil
import subprocess
import threading
import time
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Callable

from sta_lite.core.errors import UserError
from sta_lite.parsers.reports import (
    determine_risk,
    extract_warnings,
    parse_metric,
    parse_worst_paths,
    read_text,
)


LogCallback = Callable[[str], None]


@dataclass
class AnalysisConfig:
    top: str
    rtl: list[str]
    liberty_file: str
    out_dir: str
    clock: str | None = None
    period: float | None = None
    sdc_file: str | None = None
    max_paths: int = 5
    yosys_bin: str = "yosys"
    sta_bin: str = "sta"
    cwd: Path = Path.cwd()


class ProcessController:
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._process: subprocess.Popen[str] | None = None
        self._stop_requested = False

    def attach(self, process: subprocess.Popen[str]) -> None:
        with self._lock:
            self._process = process
            if self._stop_requested and process.poll() is None:
                process.terminate()

    def detach(self, process: subprocess.Popen[str]) -> None:
        with self._lock:
            if self._process is process:
                self._process = None

    def request_stop(self) -> None:
        with self._lock:
            self._stop_requested = True
            if self._process and self._process.poll() is None:
                self._process.terminate()

    @property
    def stop_requested(self) -> bool:
        with self._lock:
            return self._stop_requested


def emit(on_log: LogCallback | None, message: str) -> None:
    if on_log:
        on_log(message)


def as_posix_path(path: Path) -> str:
    return str(path.resolve())


def quote_yosys(value: str | Path) -> str:
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'


def quote_tcl(value: str | Path) -> str:
    text = str(value).replace("\\", "/").replace('"', '\\"')
    return f'"{text}"'


def write_json(path: Path, data: dict[str, Any]) -> None:
    path.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")


def require_executable(name: str, label: str) -> str:
    resolved = shutil.which(name)
    if not resolved:
        raise UserError(f"找不到 {label} 可执行文件：{name}。请先安装并确认它在 PATH 中。")
    return resolved


def require_file(path: Path, label: str) -> Path:
    if not path.is_file():
        raise UserError(f"找不到{label}：{path}")
    return path.resolve()


def expand_rtl_files(patterns: list[str]) -> list[Path]:
    files: list[Path] = []
    missing: list[str] = []
    for pattern in patterns:
        matches = sorted(glob.glob(pattern))
        if matches:
            for match in matches:
                candidate = Path(match)
                if candidate.is_file():
                    files.append(candidate.resolve())
            continue

        candidate = Path(pattern)
        if candidate.is_file():
            files.append(candidate.resolve())
        else:
            missing.append(pattern)

    if missing:
        raise UserError("找不到 RTL 文件：" + ", ".join(missing))
    if not files:
        raise UserError("没有可用的 RTL 输入文件。")

    deduped: list[Path] = []
    seen: set[Path] = set()
    for file in files:
        if file not in seen:
            deduped.append(file)
            seen.add(file)
    return deduped


def build_yosys_script(rtl_files: list[Path], top: str, liberty: Path, netlist: Path) -> str:
    rtl_args = " ".join(quote_yosys(path) for path in rtl_files)
    return "\n".join(
        [
            f"read_verilog {rtl_args}",
            f"hierarchy -check -top {top}",
            "proc",
            "opt",
            "fsm",
            "opt",
            "memory",
            "opt",
            "techmap",
            "opt",
            f"dfflibmap -liberty {quote_yosys(liberty)}",
            f"abc -liberty {quote_yosys(liberty)}",
            "clean",
            f"stat -liberty {quote_yosys(liberty)}",
            f"write_verilog -noattr {quote_yosys(netlist)}",
            "",
        ]
    )


def build_auto_sdc(clock: str, period: float) -> str:
    return "\n".join(
        [
            "# Auto-generated by sta-lite.",
            f"create_clock -name {clock} -period {period:g} [get_ports {clock}]",
            "",
        ]
    )


def build_opensta_script(
    top: str,
    liberty: Path,
    netlist: Path,
    sdc: Path,
    checks_rpt: Path,
    wns_rpt: Path,
    tns_rpt: Path,
    max_paths: int,
) -> str:
    return "\n".join(
        [
            f"read_liberty {quote_tcl(liberty)}",
            f"read_verilog {quote_tcl(netlist)}",
            f"link_design {top}",
            f"source {quote_tcl(sdc)}",
            "check_setup",
            (
                "report_checks -path_delay max "
                f"-group_count {max_paths} "
                "-fields {slew cap input nets fanout} -digits 4 "
                f"> {quote_tcl(checks_rpt)}"
            ),
            f"report_tns > {quote_tcl(tns_rpt)}",
            f"report_wns > {quote_tcl(wns_rpt)}",
            "",
        ]
    )


def run_streaming_command(
    cmd: list[str],
    cwd: Path,
    on_log: LogCallback | None,
    mirror_log: Path | None = None,
    controller: ProcessController | None = None,
) -> int:
    emit(on_log, "$ " + " ".join(cmd))
    log_handle = mirror_log.open("w", encoding="utf-8") if mirror_log else None
    try:
        process = subprocess.Popen(
            cmd,
            cwd=str(cwd),
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            bufsize=1,
        )
        if controller:
            controller.attach(process)
        assert process.stdout is not None
        for line in process.stdout:
            line = line.rstrip("\n")
            if log_handle:
                log_handle.write(line + "\n")
                log_handle.flush()
            emit(on_log, line)
        return process.wait()
    finally:
        if controller:
            try:
                controller.detach(process)  # type: ignore[name-defined]
            except UnboundLocalError:
                pass
        if log_handle:
            log_handle.close()


def make_summary(
    config: AnalysisConfig,
    rtl_files: list[Path],
    liberty: Path,
    sdc_file: Path | None,
    netlist: Path,
    out_dir: Path,
    elapsed_seconds: float,
    failure: str | None = None,
) -> dict[str, Any]:
    yosys_log = out_dir / "yosys.log"
    opensta_log = out_dir / "opensta.log"
    checks_rpt = out_dir / "checks.rpt"
    wns_rpt = out_dir / "wns.rpt"
    tns_rpt = out_dir / "tns.rpt"

    yosys_warnings = extract_warnings(read_text(yosys_log))
    opensta_warnings = extract_warnings(read_text(opensta_log) + "\n" + read_text(checks_rpt))
    wns = parse_metric(wns_rpt, "wns")
    tns = parse_metric(tns_rpt, "tns")
    worst_paths = parse_worst_paths(checks_rpt)
    timing_violations = [
        path for path in worst_paths if path.get("slack") is not None and path["slack"] < 0
    ]
    risk_level, risk_explanation = determine_risk(
        wns=wns,
        tns=tns,
        worst_paths=worst_paths,
        yosys_warnings=yosys_warnings,
        opensta_warnings=opensta_warnings,
        failure=failure,
    )

    return {
        "status": "FAILED" if failure else "OK",
        "top": config.top,
        "rtl_files": [as_posix_path(path) for path in rtl_files],
        "liberty_file": as_posix_path(liberty),
        "sdc_file": as_posix_path(sdc_file) if sdc_file else None,
        "generated_netlist": as_posix_path(netlist),
        "wns": wns,
        "tns": tns,
        "worst_paths": worst_paths,
        "timing_violations": timing_violations,
        "yosys_warnings": yosys_warnings,
        "opensta_warnings": opensta_warnings,
        "risk_level": risk_level,
        "risk_explanation_zh": risk_explanation,
        "elapsed_seconds": round(elapsed_seconds, 3),
        "artifacts": {
            "yosys_script": as_posix_path(out_dir / "synth.ys"),
            "opensta_script": as_posix_path(out_dir / "opensta.tcl"),
            "yosys_log": as_posix_path(yosys_log),
            "opensta_log": as_posix_path(opensta_log),
            "checks_report": as_posix_path(checks_rpt),
            "wns_report": as_posix_path(wns_rpt),
            "tns_report": as_posix_path(tns_rpt),
            "summary_json": as_posix_path(out_dir / "summary.json"),
        },
    }


def analyze(config: AnalysisConfig, on_log: LogCallback | None = None, controller: ProcessController | None = None) -> dict[str, Any]:
    started_at = time.monotonic()
    cwd = config.cwd.resolve()
    yosys_bin = require_executable(config.yosys_bin, "Yosys")
    sta_bin = require_executable(config.sta_bin, "OpenSTA")
    rtl_files = expand_rtl_files(config.rtl)
    liberty = require_file(Path(config.liberty_file), " Liberty 文件")

    if config.sdc_file:
        source_sdc = require_file(Path(config.sdc_file), " SDC 文件")
    else:
        if not config.clock or config.period is None:
            raise UserError("未提供 SDC 时必须同时提供时钟名和时钟周期。")
        if config.period <= 0:
            raise UserError("时钟周期必须是正数。")
        source_sdc = None

    out_dir = Path(config.out_dir).resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    netlist = out_dir / "synth.v"
    yosys_script = out_dir / "synth.ys"
    opensta_script = out_dir / "opensta.tcl"
    yosys_log = out_dir / "yosys.log"
    opensta_log = out_dir / "opensta.log"
    summary_json = out_dir / "summary.json"
    checks_rpt = out_dir / "checks.rpt"
    wns_rpt = out_dir / "wns.rpt"
    tns_rpt = out_dir / "tns.rpt"
    run_sdc = out_dir / "constraints.sdc"

    if source_sdc:
        run_sdc.write_text(read_text(source_sdc), encoding="utf-8")
        emit(on_log, f"[sta-lite] 使用用户 SDC：{source_sdc}")
    else:
        assert config.clock is not None and config.period is not None
        run_sdc.write_text(build_auto_sdc(config.clock, config.period), encoding="utf-8")
        emit(on_log, f"[sta-lite] 自动生成 SDC：clock={config.clock}, period={config.period:g} ns")

    yosys_script.write_text(build_yosys_script(rtl_files, config.top, liberty, netlist), encoding="utf-8")
    emit(on_log, "[sta-lite] 开始运行 Yosys 综合。")
    yosys_result = run_streaming_command(
        [yosys_bin, "-s", str(yosys_script), "-l", str(yosys_log)],
        cwd=cwd,
        on_log=on_log,
        mirror_log=None,
        controller=controller,
    )
    if controller and controller.stop_requested:
        failure = "用户终止了分析。"
        summary = make_summary(config, rtl_files, liberty, run_sdc, netlist, out_dir, time.monotonic() - started_at, failure)
        write_json(summary_json, summary)
        raise UserError(f"{failure} 已保存当前摘要：{summary_json}")
    if yosys_result != 0 or not netlist.is_file():
        failure = f"Yosys 综合失败，退出码 {yosys_result}。"
        summary = make_summary(config, rtl_files, liberty, run_sdc, netlist, out_dir, time.monotonic() - started_at, failure)
        write_json(summary_json, summary)
        raise UserError(f"{failure} 详情见：{yosys_log}")

    emit(on_log, f"[sta-lite] Yosys 综合完成：{netlist}")
    opensta_script.write_text(
        build_opensta_script(
            top=config.top,
            liberty=liberty,
            netlist=netlist,
            sdc=run_sdc,
            checks_rpt=checks_rpt,
            wns_rpt=wns_rpt,
            tns_rpt=tns_rpt,
            max_paths=config.max_paths,
        ),
        encoding="utf-8",
    )

    emit(on_log, "[sta-lite] 开始运行 OpenSTA 时序分析。")
    sta_result = run_streaming_command(
        [sta_bin, "-exit", str(opensta_script)],
        cwd=cwd,
        on_log=on_log,
        mirror_log=opensta_log,
        controller=controller,
    )
    if controller and controller.stop_requested:
        failure = "用户终止了分析。"
        summary = make_summary(config, rtl_files, liberty, run_sdc, netlist, out_dir, time.monotonic() - started_at, failure)
        write_json(summary_json, summary)
        raise UserError(f"{failure} 已保存当前摘要：{summary_json}")

    opensta_text = read_text(opensta_log)
    opensta_has_error = bool(re.search(r"(^Error:|\bERROR\b)", opensta_text, re.MULTILINE | re.IGNORECASE))
    missing_reports = not checks_rpt.is_file() or not wns_rpt.is_file() or not tns_rpt.is_file()
    if sta_result != 0 or opensta_has_error or missing_reports:
        reason = f"OpenSTA 分析失败，退出码 {sta_result}。"
        if opensta_has_error:
            reason = "OpenSTA 日志中出现 Error。"
        if missing_reports:
            reason = "OpenSTA 未生成完整报告。"
        summary = make_summary(config, rtl_files, liberty, run_sdc, netlist, out_dir, time.monotonic() - started_at, reason)
        write_json(summary_json, summary)
        raise UserError(f"{reason} 详情见：{opensta_log}")

    summary = make_summary(config, rtl_files, liberty, run_sdc, netlist, out_dir, time.monotonic() - started_at)
    write_json(summary_json, summary)
    emit(on_log, f"[sta-lite] OpenSTA 分析完成：WNS={summary['wns']}, TNS={summary['tns']}, 风险={summary['risk_level']}")
    emit(on_log, f"[sta-lite] summary.json 已生成：{summary_json}")
    return summary
